apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ticker-nodejs
  name: ticker-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ticker-nodejs
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: ticker-nodejs
    spec:
      hostname: ticker-nodejs
      containers:
      - name: ticker-nodejs
        tty: true
        image: ticker-nodejs
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672/%2F
        - name: QUEUE_TO
          value: test_a
        - name: TICK_INTERVAL
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ticker-nodejs
  name: ticker-nodejs
spec:
  selector:
    run: ticker-nodejs
  type: ClusterIP
  ports:
  - port: 12345
    targetPort: 12345
    protocol: TCP
---
